import type { Action, Notification } from "./game-types"

export const defaultActions: Action[] = [
  {
    id: "train-small",
    category: "TRAINING",
    name: "TTS",
    description: "Train a text-to-speech model to gain research points",
    size: "3B",
    cost: 500,
    duration: 300,
    rpReward: 120,
    reputationReward: 5,
    xpReward: 25,
    disabled: false,
    image: "/ai-neural-network-training-blue-glow.jpg",
  },
  {
    id: "train-medium",
    category: "TRAINING",
    name: "VLM",
    description: "Train a vision language model for higher rewards",
    size: "7B",
    cost: 1200,
    duration: 720,
    rpReward: 260,
    reputationReward: 12,
    xpReward: 60,
    disabled: false,
    image: "/advanced-ai-training-purple-cyber.jpg",
  },
  {
    id: "train-large",
    category: "TRAINING",
    name: "LLM",
    description: "Train a large language model for maximum research output",
    size: "13B",
    cost: 2500,
    duration: 1200,
    rpReward: 480,
    reputationReward: 25,
    xpReward: 120,
    disabled: false,
    image: "/massive-ai-datacenter-training.jpg",
  },
  {
    id: "freelance",
    category: "INCOME",
    name: "Freelance AI Contract",
    description: "Complete a contract for immediate cash payment",
    cost: 0,
    duration: 180,
    cashReward: 400,
    reputationReward: 2,
    xpReward: 10,
    cooldown: 600,
    disabled: false,
    image: "/cyberpunk-freelance-coding-terminal.jpg",
  },
  {
    id: "hire",
    category: "HIRING",
    name: "Hire Junior Researcher",
    description: "Expand your team to increase efficiency and parallel task capacity",
    cost: 1500,
    duration: 120,
    speedBonus: 10,
    parallelBonus: 1,
    disabled: false,
    image: "/hiring-tech-researcher-futuristic.jpg",
  },
  {
    id: "optimize",
    category: "OPTIMIZATION",
    name: "Optimize Infrastructure",
    description: "Reduce compute costs and improve efficiency",
    cost: 800,
    duration: 240,
    costReduction: 15,
    xpReward: 30,
    disabled: false,
    image: "/server-optimization-tech-infrastructure.jpg",
  },
]

export const defaultNotifications: Notification[] = [
  {
    id: 1,
    type: "level_up",
    title: "Level Up!",
    message: "Congratulations! You've reached Level 2. New features unlocked: Task Queue enabled.",
    timestamp: Date.now() - 300000,
  },
  {
    id: 2,
    type: "message",
    title: "Message from Dr. Chen",
    message: "Impressive progress on the small model training! Keep up the good work.",
    timestamp: Date.now() - 600000,
  },
  {
    id: 3,
    type: "task_complete",
    title: "Task Completed",
    message: "Train Small Model has finished. +120 RP, +5 Reputation, +25 XP",
    timestamp: Date.now() - 900000,
  },
]
